//ALAN DANIEL PALMA PACHECO , ESCOM , FUNDAMENTOS PROGRAMACION , CICLOS
// WHILE (CUANDO NO SEPAMOS CUANTAS VECES SE VA REPETIR UN PROCESO)
//FOR (CUANDO SI SEPAMOS CUANTAS VECES SE VA REPETIR UN PROCESO)
#include <stdio.h>
int main(){
	
	//PROGRAMA QUE SE DETENGA AL INGRESAR UN NUMERO NEGATIVO
	
	int numero = 0;
	while(numero>=0){
		scanf("%i",&numero);	
	}
	printf("\n\tYA ACABO EL PROGRAMA");
	
	return 0;
}
